export default function About() {
  return (
    <div className="space-y-5">
      <h1 className="font-display text-xl font-semibold">About WAHDATH</h1>
      <p className="text-ink-soft dark:text-white/70">
        WAHDATH is a digital companion designed to make essential Islamic tools easier to access for Muslims in
        Sri Lanka.
      </p>

      <dl className="space-y-3 text-sm">
        <Row label="Version">0.1.0 — architecture skeleton</Row>
        <Row label="Prayer times source">
          Uploaded Colombo 2026 yearly timetable (base data). Location-specific timetables are not yet verified —
          see Prayer page for details.
        </Row>
        <Row label="Qur'an source">
          Arabic (Uthmani script): The Noble Qur'an Encyclopedia (quranenc.com). English translation: Saheeh
          International, via Tanzil.net. Packaged by the quran-json project, CC BY-SA 4.0.
        </Row>
        <Row label="AI explanations">
          Generated by Claude, and only ever written about ayahs a real keyword search already retrieved —
          never about verses the AI invented itself.
        </Row>
        <Row label="Open-source libraries">React, React Router, Tailwind CSS, Vite, vite-plugin-pwa</Row>
      </dl>
    </div>
  )
}

function Row({ label, children }) {
  return (
    <div className="rounded-card border border-emerald-100 bg-white p-4 dark:border-night-line dark:bg-night-card">
      <dt className="text-xs font-medium tracking-wide text-emerald-600 dark:text-emerald-100">{label.toUpperCase()}</dt>
      <dd className="mt-1 text-ink-soft dark:text-white/70">{children}</dd>
    </div>
  )
}
